apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-opentel
  namespace: opentel
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 1s
      resource:
        attributes:
          - key: fruits.key
            value: "gateway"
            action: insert
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: my-jaeger-collector-headless.opentel.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
    service:
      telemetry:
        logs:
          level: debug
          initial_fields:
            service: fruits
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
  volumeMounts:
    - mountPath: /etc/pki/ca-trust/source/service-ca
      name: cabundle-volume
  volumes:
    - configMap:
        name: my-opentel-cabundle
      name: cabundle-volume